use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use solana_client::rpc_client::RpcClient;
use solana_sdk::{
    instruction::{AccountMeta, Instruction},
    message::Message,
    pubkey::Pubkey,
    signature::Keypair,
    signer::Signer,
    transaction::Transaction,
};

/// Seeds used by the on-chain program
const POW_CONFIG_SEED: &[u8] = b"pow_config";
const DEVICE_ATTEST_SEED: &[u8] = b"device_attest";
const POOL_SEEKER: u8 = 1;

/// Anchor instruction discriminator for `create_attestation`
/// Generated by: sha256("global:create_attestation")[0..8]
fn create_attestation_discriminator() -> [u8; 8] {
    use solana_sdk::hash::hash;
    let preimage = b"global:create_attestation";
    let h = hash(preimage);
    let mut disc = [0u8; 8];
    disc.copy_from_slice(&h.to_bytes()[..8]);
    disc
}

/// Build a `create_attestation` transaction, partially signed by the backend authority.
///
/// The miner must add their signature before submitting to Solana.
///
/// Returns: (base64-encoded partially signed transaction, attestation PDA pubkey)
pub fn build_attestation_tx(
    rpc: &RpcClient,
    program_id: &Pubkey,
    authority_keypair: &Keypair,
    miner: &Pubkey,
    rent_recipient: Option<&Pubkey>,
) -> Result<(String, Pubkey), String> {
    // Derive PDAs (attestation references Seeker pool)
    let (pow_config_pda, _pow_bump) =
        Pubkey::find_program_address(&[POW_CONFIG_SEED, &[POOL_SEEKER]], program_id);
    let (attestation_pda, _attest_bump) =
        Pubkey::find_program_address(&[DEVICE_ATTEST_SEED, miner.as_ref()], program_id);

    // Build instruction data (just the discriminator, no args)
    let data = create_attestation_discriminator().to_vec();

    // Build accounts list matching CreateAttestation struct order:
    // 1. miner (signer, mut) - will be signed by the app
    // 2. authority (signer) - signed by backend
    // 3. pow_config (read-only)
    // 4. attestation (mut, init_if_needed)
    // 5. system_program
    let accounts = vec![
        AccountMeta::new(*miner, true),
        AccountMeta::new_readonly(authority_keypair.pubkey(), true),
        AccountMeta::new_readonly(pow_config_pda, false),
        AccountMeta::new(attestation_pda, false),
        AccountMeta::new_readonly(*rent_recipient.unwrap_or(miner), false),
        AccountMeta::new_readonly(solana_sdk::system_program::id(), false),
    ];

    let instruction = Instruction {
        program_id: *program_id,
        accounts,
        data,
    };

    // Get recent blockhash
    let recent_blockhash = rpc
        .get_latest_blockhash()
        .map_err(|e| format!("Failed to get blockhash: {e}"))?;

    // Create transaction with miner as fee payer
    let message = Message::new_with_blockhash(
        &[instruction],
        Some(miner),
        &recent_blockhash,
    );

    let mut tx = Transaction::new_unsigned(message);

    // Partially sign with authority only (miner signs on the app side)
    tx.partial_sign(&[authority_keypair], recent_blockhash);

    // Serialize to base64
    let tx_bytes = bincode::serialize(&tx)
        .map_err(|e| format!("Failed to serialize transaction: {e}"))?;
    let tx_b64 = BASE64.encode(&tx_bytes);

    Ok((tx_b64, attestation_pda))
}

/// Load a Solana keypair from a JSON file (standard solana-keygen format)
pub fn load_keypair(path: &str) -> Result<Keypair, String> {
    let data = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read keypair file '{}': {e}", path))?;
    let bytes: Vec<u8> = serde_json::from_str(&data)
        .map_err(|e| format!("Failed to parse keypair JSON: {e}"))?;
    Keypair::try_from(bytes.as_slice())
        .map_err(|e| format!("Invalid keypair bytes: {e}"))
}
